### ISSUE TITLE
Error creating devices

### ISSUE THREAD

**Issue by andig** [andig/pimatic-fritz#25]
```
11:16:09.735 [pimatic] info: New device "thermostat"...
11:17:43.270 [pimatic] info: New device "thermostat-temp"...
11:18:04.453 [pimatic] info: New device "outlet"...
11:18:20.730 [pimatic] info: New device "outlet-temp"...
11:18:21.702 [pimatic-fritz] error: Cannot access undefined: undefined
Unhandled rejection TypeError: Cannot read property 'celsius' of undefined
    at /home/pi/pimatic/node_modules/pimatic-fritz/node_modules/smartfritz-promise/smartfritz.js:424:68
    at tryCatcher (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by andig** [comment]
Fixed via https://github.com/andig/pimatic-fritz/commit/117d77e9beaaaecdbbaf17f4e205486ef1dac9f6
