### ISSUE TITLE
Error Object

### ISSUE THREAD

**Issue by Alphascrypt** [andig/pimatic-fritz#26]
Nach deinem Update kommt folgender fehler:

`12:49:15.645 [pimatic-fritz] Re-establishing session at http://192.168.178.1
12:49:16.566 [pimatic-fritz] setTempTarget dacb8892da891373 109710535184 16.5
12:49:16.972 [pimatic-fritz] getTemperature dacb8892da891373 109710535184
12:49:17.330 [pimatic-fritz] Cannot access http://192.168.178.1/webservices/homeautoswitch.lua?0=0&sid=dacb8892da891373&switchcmd=getswitchtemperature&ain=109710535184: 400
12:49:17.359 [pimatic-fritz] getTemperature dacb8892da891373 109710535184
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectUncheckedCheckError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:657:22)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:556:21)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)
12:49:17.845 [pimatic-fritz] Cannot access http://192.168.178.1/webservices/homeautoswitch.lua?0=0&sid=dacb8892da891373&switchcmd=getswitchtemperature&ain=109710535184: 400
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectUncheckedCheckError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:657:22)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:556:21)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)
`

**Comment by andig** [comment]
Bitte nochmal auf 0.4.3 aktualisieren. Die Abhängigkeiten waren noch nicht korrekt.
